" Generated by vim-plug
" Sat Jan 11 21:12:22 2025
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['copilot.vim'].commit = '87038123804796ca7af20d1b71c3428d858a9124'
silent! let g:plugs['vim-bufkill'].commit = '3113181d0c1bfb8719f3ddcd2e2f35a8d763d1e5'
silent! let g:plugs['vim-commentary'].commit = '64a654ef4a20db1727938338310209b6a63f60c9'
silent! let g:plugs['vim-fanfingtastic'].commit = '6d0fea6dafbf3383dbab1463dbfb3b3d1b94b209'
silent! let g:plugs['vim-fugitive'].commit = '174230d6a7f2df94705a7ffd8d5413e27ec10a80'
silent! let g:plugs['vim-repeat'].commit = '65846025c15494983dafe5e3b46c8f88ab2e9635'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-vinegar'].commit = 'bb1bcddf43cfebe05eb565a84ab069b357d0b3d6'

PlugUpdate!

